;;;; mdcd-sections.import.scm - GENERATED BY CHICKEN 4.10.0 -*- Scheme -*-

(eval '(import chicken scheme data-structures srfi-13 srfi-1 regex))
(##sys#register-compiled-module
  'mdcd-sections
  (list)
  '((header-line-truthyness . mdcd-sections#header-line-truthyness)
    (header-indexes . mdcd-sections#header-indexes)
    (extract-section . mdcd-sections#extract-section)
    (section-line-numbers . mdcd-sections#section-line-numbers)
    (section-start . mdcd-sections#section-start)
    (line-matches-section? . mdcd-sections#line-matches-section?)
    (string-is-md-header? . mdcd-sections#string-is-md-header?))
  (list)
  (list))

;; END OF FILE
