;;;; mdcd-config.import.scm - GENERATED BY CHICKEN 4.10.0 -*- Scheme -*-

(eval '(import chicken scheme files data-structures posix))
(##sys#register-compiled-module
  'mdcd-config
  (list)
  '((set-mdcd-home . mdcd-config#set-mdcd-home)
    (get-mdcd-home . mdcd-config#get-mdcd-home)
    (mdcd-enabled? . mdcd-config#mdcd-enabled?)
    (mdcd-disable . mdcd-config#mdcd-disable)
    (mdcd-use-default-home . mdcd-config#mdcd-use-default-home)
    (get-mdcd-home-dirs . mdcd-config#get-mdcd-home-dirs)
    (mdcd-default-home-dirs . mdcd-config#mdcd-default-home-dirs))
  (list)
  (list))

;; END OF FILE
