;;;; mdcd.import.scm - GENERATED BY CHICKEN 4.10.0 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         files
         directory-utils
         data-structures
         utils
         regex
         mdcd-config
         (prefix mdcd-sections ms:)))
(##sys#register-compiled-module
  'mdcd
  (list)
  '((doc-fun . mdcd#doc-fun)
    (doc-syntax . mdcd#doc-syntax)
    (doc-var . mdcd#doc-var)
    (show-doc . mdcd#show-doc)
    (read-doc . mdcd#read-doc)
    (show-description . mdcd#show-description)
    (show-params . mdcd#show-params)
    (show-returns . mdcd#show-returns)
    (show-examples . mdcd#show-examples)
    (show-notes . mdcd#show-notes)
    (show-section . mdcd#show-section)
    (mdcd-path-for-var . mdcd#mdcd-path-for-var)
    (mdcd-path-for-fun . mdcd#mdcd-path-for-fun)
    (mdcd-path-for-syntax . mdcd#mdcd-path-for-syntax))
  (list)
  (list))

;; END OF FILE
